# SPDX-FileCopyrightText: Copyright (c) 2019-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: up
'on':
  push:
jobs:
  up:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: |-
          git fetch --tags --force && \
          latest=$(git tag --sort=creatordate | tail -1) && \
          sed -E -i "s/drops@[0-9.]+/drops@${latest}/g" README.md
          sed -E -i "s/drops-[0-9.]+\.min/drops-${latest}.min/g" README.md
      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'new version in README'
          delete-branch: true
          title: 'New version in README'
          assignees: yegor256
          branch: up
          base: master
